services:
  app:
    build:
      context: ./
      network: host
    image: nvim_blink
    network_mode: host
    stop_signal: SIGKILL
    volumes:
      - ./config:/root/.config/nvim
      - ./examples:/root/examples
    working_dir: /root/examples
    command: tail -f /dev/null
