services:
  app:
    build:
      context: ./
      network: host
    image: nvim_blink
    network_mode: host
    stop_signal: SIGINT
    volumes:
      - ./config:/root/.config/nvim
      - ./examples:/root/examples
    command: sleep infinity
